export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next + Sanity",
};

export default function StudioLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
